// This file should be auto-generated by the Firebase CLI or FlutterFire CLI
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyApM1zNsqZK8E_-uWpy1De6JIlLa0poIw4',
      appId: '1:510654992394:android:0025946678d1b6a6ffcff3',
      messagingSenderId: '510654992394',
      projectId: 'bite-express-b3634',
    );
  }
}